name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "^1.13.1"

      - name: build game
        run: |
          go install github.com/tmedwards/tweego@master
          export PATH=$PATH:$(go env GOPATH)/bin
          tweego -o index.html main.twee

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: /
